@echo off
echo Starting Random IT Solutions Website...
echo.
echo Installing dependencies...
call npm install
echo.
echo Starting development server...
call npx cross-env NODE_ENV=development tsx server/index.ts